### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by Arinod** [NJUPTFreeExams/NJUPT-CS-Free-Exams#13]
兄弟你这里面的文件在线也看不到，也无法下载。全项目克隆很大啊一直超时，下载单个文件的Download没用，是不是中文链接的原因。真的啥也看不了😥

**Comment by gzr-lgtm** [comment]
After some random tests, I cannot find any file that cannot be downloaded. Please check your network settings, or give links of specific non-available files. FYI, sometimes you may experience such bad experience "thanks" to the GFW.....
